export const FILTER = 'FILTER';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

// common
export const SET_PROPERTIES = 'SET_PROPERTIES';
export const SET_GENERAL_MESSAGE = 'SET_GENERAL_MESSAGE';
export const REMOVE_GENERAL_MESSAGE = 'REMOVE_GENERAL_MESSAGE';
export const SET_CORPORATES = 'SET_CORPORATES';
export const DELETE_CORPORATE = 'DELETE_CORPORATE';
export const SET_USERS = 'SET_USERS';
export const SET_STATES = 'SET_STATES';

// uploadContracts
export const CREATE_CONTRACT = 'CREATE_CONTRACT';
export const SET_CONTRACTS = 'SET_CONTRACTS';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_ERRORS_BY_CONTRACTS = 'SET_ERRORS_BY_CONTRACTS';
export const SET_NUMBER_OF_CONTRACTS = 'SET_NUMBER_OF_CONTRACTS';
export const REMOVE_ERRORS_BY_CONCTRACTS = 'REMOVE_ERRORS_BY_CONCTRACTS';
export const SET_PROPERTY_AND_CREATED_BY = 'SET_PROPERTY_AND_CREATED_BY';
export const UPLOAD_CONTRACTS_SET_UPDATE_PROPERTY_CONTRACT = 'UPLOAD_CONTRACTS_SET_UPDATE_PROPERTY_CONTRACT';


// createCorporateContractPage
export const SET_SELECTED_CORPORATE = 'SET_SELECTED_CORPORATE';
export const CREATE_CORPORATE_SET_SEARCH_PROPERTY_ID = 'CREATE_CORPORATE_SET_SEARCH_PROPERTY_ID';
export const CREATE_CORPORATE_SET_CONTRACTS = 'CREATE_CORPORATE_SET_CONTRACTS';
export const CREATE_CORPORATE_SET_SINGLE_CONTRACT = 'CREATE_CORPORATE_SET_SINGLE_CONTRACT';
export const CREATE_CORPORATE_SET_CONTRACTS_SHOW_IDS = 'CREATE_CORPORATE_SET_CONTRACTS_SHOW_IDS';

// Bulk Corporate Contract
export const SET_RESPONSE_DATA = 'SET_RESPONSE_DATA';
export const SET_FILE_NAME = 'SET_FILE_NAME';

// ViewDefaultCorporateContracts
export const SET_DEFAULT_CORPORATE_CONTRACT = 'SET_DEFAULT_CORPORATE_CONTRACT';

// corporateDetailsPage
export const CORPORATE_DETAILS_DELETE_CLICKED = 'CORPORATE_DETAILS_DELETE_CLICKED';
export const CORPORATE_DETAILS_MODAL_NO_CLICKED = 'CORPORATE_DETAILS_MODAL_NO_CLICKED';
export const CORPORATE_DETAILS_DELETED_SUCCESS_OR_FAILED = 'CORPORATE_DETAILS_DELETED_SUCCESS_OR_FAILED';

// createOrUpdateCorporate
export const SET_NEW_CORPORATE = 'SET_NEW_CORPORATE';
export const SET_UPDATE_CORPORATE = 'SET_UPDATE_CORPORATE';
export const SET_DEFAULT_CORPORATE = 'SET_DEFAULT_CORPORATE';

// userCorporateMapping


// logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// login
export const LOGIN_REQUEST_INIT = 'LOGIN_REQUEST_INIT';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
export const LOGIN_OTP_VALIDATION_INIT = 'LOGIN_OTP_VALIDATION_INIT';
export const LOGIN_OTP_VALIDATION_SUCCESS = 'LOGIN_OTP_VALIDATION_SUCCESS';
export const LOGIN_OTP_VALIDATION_FAILED = 'LOGIN_OTP_VALIDATION_FAILED';

export const LOGIN_OTP_RESEND_INIT = 'LOGIN_OTP_RESEND_INIT';
export const LOGIN_OTP_RESEND_SUCCESS = 'LOGIN_OTP_RESEND_SUCCESS';
export const LOGIN_OTP_RESEND_FAILED = 'LOGIN_OTP_RESEND_FAILED';
export const LOGIN_RESET_STORE = 'LOGIN_RESET_STORE';


